# seems to work only on the cluster with enable-kubernetes-alpha selected
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2alpha1
metadata:
  name: hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dep
  # targetCPUUtilizationPercentage: 80 # v1 stuff
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
  # - type: Pods
  #   pods:
  #     metricName: packets-per-second
  #     targetAverageValue: 1k
