kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-www
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
  storageClassName: slow
  # selector:
  #   matchLabels:
  #     release: stable
